# Generated by Django 5.0.7 on 2024-09-14 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpotifyToken',
            new_name='UserToken',
        ),
    ]
