# Generated by Django 5.0.7 on 2024-09-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_rename_spotifytoken_usertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='expires_in',
            field=models.DateTimeField(),
        ),
    ]
