# Generated by Django 5.0.7 on 2024-09-15 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='current_song',
        ),
    ]
