# Generated by Django 5.0.7 on 2024-09-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0005_remove_votes_current_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='access_token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='refresh_token',
            field=models.CharField(max_length=255),
        ),
    ]
