# Generated by Django 5.2 on 2025-04-30 19:05

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=core.utils.generate_unique_code, help_text='Unique code to identify and join the room', max_length=8, unique=True)),
                ('host', models.CharField(help_text='Session ID of the room host', max_length=50, unique=True)),
                ('guest_can_pause', models.BooleanField(default=False, help_text='Whether guests can pause/play music')),
                ('votes_to_skip', models.IntegerField(default=1, help_text='Number of votes required to skip a song')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the room was created')),
                ('current_song', models.CharField(blank=True, help_text='ID of the currently playing song', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['-created_at'],
            },
        ),
    ]
