# Generated by Django 5.2 on 2025-05-04 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roomify_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(help_text='Session ID of the user', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the token was created')),
                ('access_token', models.CharField(help_text='Spotify access token', max_length=255)),
                ('refresh_token', models.CharField(help_text='Spotify refresh token', max_length=255)),
                ('token_type', models.CharField(help_text="Type of token (usually 'Bearer')", max_length=50)),
                ('expires_in', models.DateTimeField(help_text='When the token expires')),
            ],
            options={
                'verbose_name': 'Spotify Token',
                'verbose_name_plural': 'Spotify Tokens',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(help_text='Session ID of the user who voted', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the vote was cast')),
                ('song_id', models.CharField(help_text='Spotify ID of the song being voted to skip', max_length=50)),
                ('room', models.ForeignKey(help_text='Room where the vote was cast', on_delete=django.db.models.deletion.CASCADE, to='roomify_api.room')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'unique_together': {('user', 'room', 'song_id')},
            },
        ),
    ]
